# Generated by Django 4.0.3 on 2022-03-17 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='Book',
        ),
    ]
