# Generated by Django 4.0.3 on 2022-03-24 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='Length',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='film',
            old_name='Year',
            new_name='year',
        ),
    ]
