# Generated by Django 4.0.3 on 2022-04-11 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('func_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='s_no',
            field=models.IntegerField(default=True),
        ),
    ]
