# Generated by Django 4.0.3 on 2022-04-18 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='belongs_to',
            new_name='region',
        ),
    ]
