# Generated by Django 4.0.3 on 2022-04-18 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_company_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='region',
            new_name='user',
        ),
    ]
