# Generated by Django 4.0.3 on 2022-04-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_region_company_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='joing_date',
            field=models.CharField(max_length=10),
        ),
    ]
