# Generated by Django 4.0.3 on 2022-03-14 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=200)),
                ('Book_desc', models.TextField()),
                ('Entry_time', models.DateTimeField()),
            ],
        ),
    ]
