# Generated by Django 4.0.3 on 2022-03-11 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_title', models.CharField(max_length=200)),
                ('Book_desc', models.TextField()),
            ],
        ),
    ]
